name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - Diagram
jobs:
  get_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,./scripts,./docs,.gitignore"
          file_colors: '{"lean" : "#dc4ac2ff"}'
